### ISSUE TITLE
4.7.0 ATAK crash and route fail stack trace

### ISSUE THREAD

**Issue by MightyBakedPotato** [L-Belluomini/OTN#13]
[logs_TOMMY_2022-10-02T07-58-20Z.zip](https://github.com/L-Belluomini/OTN/files/9692098/logs_TOMMY_2022-10-02T07-58-20Z.zip)

**Comment by L-Belluomini** [comment]
gson does not correctly create the ghconfig object, the profile list does not exist.
ON the sdk I was not able to replicate the issue, even tho I found another issue.....
