### ISSUE TITLE
Graphic update to comply with Arsenal guidelines

### ISSUE THREAD

**Issue by MightyBakedPotato** [L-Belluomini/OTN#14]
https://www.figma.com/file/O5KeQdPvAIHkXJqUt4J3xB/ARSENAL---ATAK-Design-System

**Comment by MightyBakedPotato** [comment]
![Image](https://user-images.githubusercontent.com/99042539/194712683-a5d4fead-20b4-4fff-9ce2-3211ed35408c.png)



![Image](https://user-images.githubusercontent.com/99042539/194713014-1047e0e2-2837-499d-a89c-e06a81cd2b75.png)

"failled setting bundle" error after working on the layout, not sure how that's happening. @L-Belluomini uploaded commit if you want to check it out (a87898a06406a2ac792e5ca4ab0fd7c000e6e3ec)

**Comment by MightyBakedPotato** [comment]
[Android TextView: Getting "W/StaticLayout: maxLineHeight should not be -1. maxLines:1 lineCount:1" when setting text](https://stackoverflow.com/questions/49416089/android-textview-getting-w-staticlayout-maxlineheight-should-not-be-1-maxli)

~~Still not solved~~ Solved graph visualization, above link still worth checking out tho

**Comment by MightyBakedPotato** [comment]
Big improvements on last commit (d8cc5840), waypoint dialog almost ready

**Comment by L-Belluomini** [comment]
status ?

**Comment by MightyBakedPotato** [comment]
Some minor corrections on colours/dimensions.
Settled on a middle ground between ARSENAL guidelines and current ATAK GUI design to keep things as consistent as possible.

**Comment by MightyBakedPotato** [comment]
Pretty much done, closing the issue
